name: Auto Merge PR from Dev to Main

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Merge PR to main
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout main
          git merge --no-ff --no-edit ${{ github.event.pull_request.head.ref }}
          git commit --amend --no-edit
          git push origin main
