name: Merge dev into main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Clone repository
        run: git clone https://github.com/whoami-anoint/auto_pr_mg

      - name: Fetch dev branch
        run: |
          cd your-repo
          git fetch origin dev

      - name: Merge dev into main
        run: |
          cd your-repo
          git checkout main
          git merge --no-ff --no-edit origin/dev

      - name: Push changes to main
        run: |
          cd your-repo
          git push origin main
