name: Automerge PR from dev to main

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge dev into main
        run: |
          git config user.name "whoami-anoint"
          git config user.email "abhishekkfl@gmail.com"
          git fetch origin ${{ github.head_ref }}
          git checkout main
          git merge ${{ github.head_ref }} --no-edit
          git push origin main

      - name: Close pull request
        uses: peter-evans/close-pull-request@v2
        with:
          comment: "This pull request has been automatically merged into main."
          delete-branch: true
